create table if not exists public.trade_agent_payments (
  id bigint generated by default as identity primary key,
  payment_tx_hash text not null unique,
  payer_address text not null,
  fee_token_address text not null,
  fee_recipient text not null,
  fee_amount_wei text not null,
  action_type text not null,
  model text,
  input_tokens integer,
  output_tokens integer,
  total_tokens integer,
  status text not null default 'pending',
  error_message text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.trade_agent_payments enable row level security;

create index if not exists trade_agent_payments_payer_created_idx
  on public.trade_agent_payments (payer_address, created_at desc);
